<?php
echo abs(-42);
echo "\n";
echo abs(42);
echo "\n";
echo floor(4.7);
echo "\n";
echo ceil(4.3);
echo "\n";
echo round(4.5);
echo "\n";
echo round(4.4);
echo "\n";
echo min(3, 1, 2);
echo "\n";
echo max(3, 1, 2);
echo "\n";
echo min([5, 3, 8, 1]);
echo "\n";
echo max([5, 3, 8, 1]);
echo "\n";
echo gettype(42);
echo "\n";
echo gettype(3.14);
echo "\n";
echo gettype('hello');
echo "\n";
echo gettype(true);
echo "\n";
echo gettype(null);
echo "\n";
echo gettype([1, 2]);
echo "\n";
$x = 42;
$y = null;
echo isset($x) ? 'true' : 'false';
echo "\n";
echo isset($y) ? 'true' : 'false';
echo "\n";
echo empty('') ? 'true' : 'false';
echo "\n";
echo empty('hello') ? 'true' : 'false';
echo "\n";
echo empty(0) ? 'true' : 'false';
echo "\n";
echo empty(1) ? 'true' : 'false';
echo "\n";
