<?php
echo pow(2, 10);
echo "\n";
echo sqrt(144);
echo "\n";
echo round(log(M_E));
echo "\n";
echo round(log(8, 2));
echo "\n";
echo round(log10(1000));
echo "\n";
echo round(exp(0));
echo "\n";
echo intdiv(7, 2);
echo "\n";
echo round(fmod(10, 3));
echo "\n";
echo dechex(255);
echo "\n";
echo hexdec("ff");
echo "\n";
echo decbin(10);
echo "\n";
echo bindec("1010");
echo "\n";
echo decoct(8);
echo "\n";
echo octdec("10");
echo "\n";
echo base_convert("ff", 16, 10);
echo "\n";
