<?php
$s = "héllo wörld";
echo mb_strlen($s), "\n";
echo strlen($s), "\n";
echo mb_substr($s, 0, 5), "\n";
echo mb_substr($s, -5), "\n";
echo mb_strtolower("HéLLO WÖRLD"), "\n";
echo mb_strtoupper("héllo wörld"), "\n";
echo mb_strpos($s, "ö"), "\n";
echo mb_strrpos($s, "l"), "\n";
echo mb_stripos("HÉLLO", "é"), "\n";
print_r(mb_str_split("héllo"));
echo mb_substr_count("ababab", "ab"), "\n";
echo mb_strstr("hello world", "wo"), "\n";
echo mb_strtolower("STRASSE") === "strasse" ? "ok\n" : "fail\n";
echo mb_strtoupper("straße"), "\n";
echo mb_convert_case("hello world", MB_CASE_TITLE), "\n";
echo mb_convert_case("HELLO WORLD", MB_CASE_LOWER), "\n";
$emoji = "😀😀😀";
echo mb_strlen($emoji), "\n";
echo strlen($emoji), "\n";
echo mb_substr($emoji, 1, 1), "\n";
echo mb_str_pad("héllo", 10, "*"), "|\n";
echo mb_str_pad("héllo", 10, "*", STR_PAD_LEFT), "|\n";
preg_match("/^héllo$/u", "héllo", $m);
print_r($m);
preg_match_all("/\\w+/u", "café résumé", $m);
print_r($m);
echo mb_check_encoding("héllo", "UTF-8") ? "valid\n" : "invalid\n";
echo mb_check_encoding("\xff\xfe", "UTF-8") ? "valid\n" : "invalid\n";
echo mb_detect_encoding("héllo", ["UTF-8", "ASCII"]), "\n";
echo mb_ord("é"), "\n";
echo mb_chr(233), "\n";
