const std = @import("std");

// parameter names for native functions, enabling named argument resolution.
// only covers commonly-used functions - unlisted functions fall back to positional args.
// names include the $ prefix to match php convention and user-defined function param format.

pub const map = std.StaticStringMap([]const []const u8).initComptime(.{
    .{ "Deprecated::__construct", &.{ "$message", "$since" } },
    .{ "substr", &.{ "$string", "$offset", "$length" } },
    .{ "str_replace", &.{ "$search", "$replace", "$subject", "$count" } },
    .{ "str_ireplace", &.{ "$search", "$replace", "$subject", "$count" } },
    .{ "explode", &.{ "$separator", "$string", "$limit" } },
    .{ "implode", &.{ "$separator", "$array" } },
    .{ "join", &.{ "$separator", "$array" } },
    .{ "str_pad", &.{ "$string", "$length", "$pad_string", "$pad_type" } },
    .{ "str_repeat", &.{ "$string", "$times" } },
    .{ "str_contains", &.{ "$haystack", "$needle" } },
    .{ "str_starts_with", &.{ "$haystack", "$needle" } },
    .{ "str_ends_with", &.{ "$haystack", "$needle" } },
    .{ "strpos", &.{ "$haystack", "$needle", "$offset" } },
    .{ "stripos", &.{ "$haystack", "$needle", "$offset" } },
    .{ "strrpos", &.{ "$haystack", "$needle", "$offset" } },
    .{ "substr_count", &.{ "$haystack", "$needle", "$offset", "$length" } },
    .{ "substr_replace", &.{ "$string", "$replace", "$offset", "$length" } },
    .{ "str_split", &.{ "$string", "$length" } },
    .{ "str_shuffle", &.{"$string"} },
    .{ "str_word_count", &.{ "$string", "$format", "$characters" } },
    .{ "strcasecmp", &.{ "$string1", "$string2" } },
    .{ "strcmp", &.{ "$string1", "$string2" } },
    .{ "strncasecmp", &.{ "$string1", "$string2", "$length" } },
    .{ "strncmp", &.{ "$string1", "$string2", "$length" } },
    .{ "strtr", &.{ "$string", "$from", "$to" } },
    .{ "ucfirst", &.{"$string"} },
    .{ "lcfirst", &.{"$string"} },
    .{ "ucwords", &.{ "$string", "$separators" } },
    .{ "strip_tags", &.{ "$string", "$allowed_tags" } },
    .{ "addslashes", &.{"$string"} },
    .{ "stripslashes", &.{"$string"} },
    .{ "bin2hex", &.{"$string"} },
    .{ "hex2bin", &.{"$string"} },
    .{ "base64_encode", &.{"$string"} },
    .{ "base64_decode", &.{ "$string", "$strict" } },
    .{ "wordwrap", &.{ "$string", "$width", "$break", "$cut_long_words" } },
    .{ "number_format", &.{ "$num", "$decimals", "$decimal_separator", "$thousands_separator" } },
    .{ "sprintf", &.{"$format"} },
    .{ "trim", &.{ "$string", "$characters" } },
    .{ "ltrim", &.{ "$string", "$characters" } },
    .{ "rtrim", &.{ "$string", "$characters" } },
    .{ "htmlspecialchars", &.{ "$string", "$flags", "$encoding", "$double_encode" } },
    .{ "nl2br", &.{ "$string", "$use_xhtml" } },
    .{ "parse_url", &.{ "$url", "$component" } },
    .{ "parse_str", &.{ "$string", "$result" } },
    .{ "http_build_query", &.{ "$data", "$numeric_prefix", "$arg_separator", "$encoding_type" } },
    .{ "http_get_last_response_headers", &.{} },
    .{ "http_clear_last_response_headers", &.{} },
    .{ "urlencode", &.{"$string"} },
    .{ "urldecode", &.{"$string"} },
    .{ "rawurlencode", &.{"$string"} },
    .{ "rawurldecode", &.{"$string"} },

    .{ "mb_strlen", &.{ "$string", "$encoding" } },
    .{ "mb_substr", &.{ "$string", "$start", "$length", "$encoding" } },
    .{ "mb_strpos", &.{ "$haystack", "$needle", "$offset", "$encoding" } },
    .{ "mb_stripos", &.{ "$haystack", "$needle", "$offset", "$encoding" } },
    .{ "mb_strrpos", &.{ "$haystack", "$needle", "$offset", "$encoding" } },
    .{ "mb_strtolower", &.{ "$string", "$encoding" } },
    .{ "mb_strtoupper", &.{ "$string", "$encoding" } },

    .{ "in_array", &.{ "$needle", "$haystack", "$strict" } },
    .{ "array_search", &.{ "$needle", "$haystack", "$strict" } },
    .{ "array_key_exists", &.{ "$key", "$array" } },
    .{ "array_keys", &.{ "$array", "$filter_value", "$strict" } },
    .{ "array_values", &.{"$array"} },
    .{ "array_flip", &.{"$array"} },
    .{ "array_replace", &.{"$array"} },
    .{ "array_count_values", &.{"$array"} },
    .{ "array_key_first", &.{"$array"} },
    .{ "array_key_last", &.{"$array"} },
    .{ "array_is_list", &.{"$array"} },
    .{ "array_sum", &.{"$array"} },
    .{ "array_product", &.{"$array"} },
    .{ "array_shift", &.{"$array"} },
    .{ "array_pop", &.{"$array"} },
    .{ "array_rand", &.{ "$array", "$num" } },
    .{ "array_map", &.{ "$callback", "$array" } },
    .{ "array_filter", &.{ "$array", "$callback", "$mode" } },
    .{ "array_slice", &.{ "$array", "$offset", "$length", "$preserve_keys" } },
    .{ "array_splice", &.{ "$array", "$offset", "$length", "$replacement" } },
    .{ "array_combine", &.{ "$keys", "$values" } },
    .{ "array_chunk", &.{ "$array", "$length", "$preserve_keys" } },
    .{ "array_column", &.{ "$array", "$column_key", "$index_key" } },
    .{ "array_fill", &.{ "$start_index", "$count", "$value" } },
    .{ "array_fill_keys", &.{ "$keys", "$value" } },
    .{ "array_unique", &.{ "$array", "$flags" } },
    .{ "array_reverse", &.{ "$array", "$preserve_keys" } },
    .{ "array_pad", &.{ "$array", "$length", "$value" } },
    .{ "array_reduce", &.{ "$array", "$callback", "$initial" } },
    .{ "array_walk", &.{ "$array", "$callback", "$arg" } },
    .{ "array_walk_recursive", &.{ "$array", "$callback", "$arg" } },
    .{ "usort", &.{ "$array", "$callback" } },
    .{ "uasort", &.{ "$array", "$callback" } },
    .{ "uksort", &.{ "$array", "$callback" } },
    .{ "compact", &.{"$var_name"} },
    .{ "range", &.{ "$start", "$end", "$step" } },

    .{ "intval", &.{ "$value", "$base" } },
    .{ "settype", &.{ "$var", "$type" } },
    .{ "call_user_func", &.{"$callback"} },
    .{ "version_compare", &.{ "$version1", "$version2", "$operator" } },

    .{ "json_encode", &.{ "$value", "$flags", "$depth" } },
    .{ "json_decode", &.{ "$json", "$associative", "$depth", "$flags" } },

    .{ "round", &.{ "$num", "$precision", "$mode" } },
    .{ "rand", &.{ "$min", "$max" } },
    .{ "mt_rand", &.{ "$min", "$max" } },
    .{ "base_convert", &.{ "$num", "$from_base", "$to_base" } },
    .{ "abs", &.{"$num"} },
    .{ "floor", &.{"$num"} },
    .{ "ceil", &.{"$num"} },

    .{ "file_get_contents", &.{ "$filename", "$use_include_path", "$context", "$offset", "$length" } },
    .{ "file_put_contents", &.{ "$filename", "$data", "$flags", "$context" } },
    .{ "fopen", &.{ "$filename", "$mode", "$use_include_path", "$context" } },
    .{ "fread", &.{ "$stream", "$length" } },
    .{ "fwrite", &.{ "$stream", "$data", "$length" } },
    .{ "mkdir", &.{ "$directory", "$permissions", "$recursive", "$context" } },
    .{ "scandir", &.{ "$directory", "$sorting_order", "$context" } },
    .{ "glob", &.{ "$pattern", "$flags" } },
    .{ "file_exists", &.{"$filename"} },
    .{ "is_file", &.{"$filename"} },
    .{ "is_dir", &.{"$filename"} },
    .{ "is_readable", &.{"$filename"} },
    .{ "is_writable", &.{"$filename"} },
    .{ "copy", &.{ "$from", "$to", "$context" } },
    .{ "rename", &.{ "$from", "$to", "$context" } },
    .{ "unlink", &.{ "$filename", "$context" } },
    .{ "chmod", &.{ "$filename", "$permissions" } },
    .{ "touch", &.{ "$filename", "$mtime", "$atime" } },
    .{ "pathinfo", &.{ "$path", "$flags" } },
    .{ "basename", &.{ "$path", "$suffix" } },
    .{ "dirname", &.{ "$path", "$levels" } },

    .{ "preg_match", &.{ "$pattern", "$subject", "$matches", "$flags", "$offset" } },
    .{ "preg_match_all", &.{ "$pattern", "$subject", "$matches", "$flags", "$offset" } },
    .{ "preg_replace", &.{ "$pattern", "$replacement", "$subject", "$limit", "$count" } },
    .{ "preg_split", &.{ "$pattern", "$subject", "$limit", "$flags" } },

    .{ "date", &.{ "$format", "$timestamp" } },
    .{ "mktime", &.{ "$hour", "$minute", "$second", "$month", "$day", "$year" } },
    .{ "strtotime", &.{ "$datetime", "$baseTimestamp" } },

    .{ "password_hash", &.{ "$password", "$algo", "$options" } },
    .{ "password_verify", &.{ "$password", "$hash" } },
    .{ "hash", &.{ "$algo", "$data", "$binary", "$options" } },
    .{ "hash_hmac", &.{ "$algo", "$data", "$key", "$binary" } },
    .{ "hash_equals", &.{ "$known_string", "$user_string" } },
    .{ "hash_pbkdf2", &.{ "$algo", "$password", "$salt", "$iterations", "$length", "$binary", "$options" } },
    .{ "random_int", &.{ "$min", "$max" } },

    .{ "var_dump", &.{"$value"} },
    .{ "print_r", &.{ "$value", "$return" } },
    .{ "var_export", &.{ "$value", "$return" } },

    .{ "setcookie", &.{ "$name", "$value", "$expires_or_options", "$path", "$domain", "$secure", "$httponly" } },
});
